### ISSUE TITLE
Marked@0.3.5 throwing 'undefined is not a function'

### ISSUE THREAD

**Issue by enykeev** [mikaelbr/cli-usage#1]
Between marked 0.3.3 and 0.3.5, `mversion -h` started throwing an error:

```
$ mversion -h
/usr/local/lib/node_modules/mversion/node_modules/cli-usage/node_modules/marked/lib/marked.js:1226
    throw e;
          ^
TypeError: undefined is not a function
Please report this to https://github.com/chjj/marked.
    at InlineLexer.output (/usr/local/lib/node_modules/mversion/node_modules/cli-usage/node_modules/marked/lib/marked.js:685:28)
    at Parser.tok (/usr/local/lib/node_modules/mversion/node_modules/cli-usage/node_modules/marked/lib/marked.js:985:21)
    at Parser.parse (/usr/local/lib/node_modules/mversion/node_modules/cli-usage/node_modules/marked/lib/marked.js:935:17)
    at Function.Parser.parse (/usr/local/lib/node_modules/mversion/node_modules/cli-usage/node_modules/marked/lib/marked.js:922:17)
    at marked (/usr/local/lib/node_modules/mversion/node_modules/cli-usage/node_modules/marked/lib/marked.js:1218:19)
    at fromFile (/usr/local/lib/node_modules/mversion/node_modules/cli-usage/index.js:45:10)
    at get (/usr/local/lib/node_modules/mversion/node_modules/cli-usage/index.js:30:12)
    at module.exports (/usr/local/lib/node_modules/mversion/node_modules/cli-usage/index.js:22:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/mversion/bin/cli.js:9:1)
    at Module._compile (module.js:460:26)
```

Manually rolling back marked to 0.3.3 solves the problem. Sorry, I'm kind of lazy to dig any deeper =)

**Comment by mikaelbr** [comment]
Thanks for letting me know! Patched and fixed! Was an error with a dependency
